baseURL = "https://example.org"
theme = "hugo_theme_adam_eve"
DefaultContentLanguage = "en"
# Enable Emoji, regarding https://www.webfx.com/tools/emoji-cheat-sheet/
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.105.0"

[Languages]
[Languages.fr]
languageCode = "fr"
title = "Ã€ propos d'aquarium"

[Languages.en]
languageCode = "en"
title = "About aquarium"

[Languages.fr.params]
description = "Des poissons et de l'eau"

[Languages.en.params]
description = "Fish and water"

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1
